api:
  cors_allowed_origins: ["*"] #TODO: change the allowed CORS to accept the requests only from frontend
  host: 0.0.0.0
  port: 8000

logger:
  logging_level: 1

board_config:
  output_cream: 2
  output_espresso: 3
