name: Pylint Code Scanning

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pylint:
    name: Run Pylint and Upload SARIF
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-sarif
        pip install -r backend/requirements.txt

    - name: Run Pylint and output to JSON
      run: |
        PYTHONPATH=. pylint backend/ --output-format=json:pylint-output.json

    - name: Convert Pylint JSON to SARIF
      run: |
        pylint-json2sarif -i pylint-output.json -o pylint-output.sarif

    - name: Upload SARIF to GitHub
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: pylint-output.sarif
